stages:
  - deploy

deploy_job:
  stage: deploy
  script:
    - echo "$GITHUB_TOKEN" > /etc/ssl/certs/github_token.pem
    - git config --global http.sslCAInfo /etc/ssl/certs/github_token.pem
    - git remote add github https://github.com/yun-ink/timerx.git
    - git remote -v
    - git push github master
  only:
    - master
    - tags